ALTER TYPE track_enum ADD VALUE IF NOT EXISTS 'LONG_EQUITY';
ALTER TYPE track_enum ADD VALUE IF NOT EXISTS 'REIT';
ALTER TYPE track_enum ADD VALUE IF NOT EXISTS 'BOND';
ALTER TYPE track_enum ADD VALUE IF NOT EXISTS 'OPTIONS';
